import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const goli = localFont({
  src: "./fonts/GoliVF.ttf",
  weight: "300, 400, 500, 600, 700",
  variable: "--font-goli",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${goli.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
